### ISSUE TITLE
与mod矿物词典的兼容

### ISSUE THREAD

**Issue by 1a2s3d4f1** [ruhuasiyu/CraftingPlusPlus#12]
[cotton resources](https://www.curseforge.com/minecraft/mc-mods/cotton-resources)添加了利用了原版数据包达到矿物词典，Crafting++也有矿物词典，所以Crafting++与mod的矿物词典兼容有可能吗
在datapacks\cotton_generated\data\c\tags\items 文件copper_dust.json
`
{ 
	"replace": false,
	"values": [ 
		"c:copper_dust"
	]
}
`

**Comment by ruhuasiyu** [comment]
不可能。因为数据包使用的物品并没有注册id
