### ISSUE TITLE
与 OptiFine 1.14.4 HD U F4 pre4 不兼容

### ISSUE THREAD

**Issue by NPBeta** [ruhuasiyu/CraftingPlusPlus#14]
只要使用了 OptiFine ，就无法正常显示模组机器的界面、模组物品的材质，但实体形式的材质可以正常显示。
自定义实体模型、自定义物品、自定义界面均已开启。
我的 OptiFine 是以 Forge Mod 形式加载的。尝试过更改设置无效。
版本：OptiFine 1.14.4 HD U F4 pre4，Forge 28.1.0.
ps：貌似与 OptiFine 和 Forge 无关，此 bug 是在模组更新为某个版本之后（貌似是 1.9.9 ？具体记不清了，之前的正常，之后的都不行）出现的。
----- 以下不是 bug -----
方块破坏器的 Wiki 貌似不是很完整，希望能够补充一下，目前不是很理解“方块破坏器已被上锁”的意思；而且希望方块破坏器空载时，可以直接右击破坏器上方来放置方块而不是需要潜行才能放置（也许取消顶部的触发就可以？毕竟上方放置方块之后，破坏器的顶部并不能被选中）。
感谢。

**Comment by NPBeta** [comment]
无法正常显示是指，会显示为对应的原版物品的材质。功能是正常使用的。

**Comment by ruhuasiyu** [comment]
尝试关闭Optifine的自定义材质等功能来解决？

方块破坏器实际上是一个上锁的容器，所以右键自然会有提示。
“方块破坏器空载时，可以直接右击破坏器上方来放置方块而不是需要潜行才能放置”，做不到这个功能，实际上你可以在隔壁放一个方块然后贴着那个方块放就行了，而且现在可以用红石自动化不必手动执行方块破坏器。

**Comment by NPBeta** [comment]
分别尝试过，界面不显示和物品栏材质错误的问题都不能解决。怀疑是与 OptiFine 的自定义材质接口不匹配所致。
方块破坏器用红石解决了，感谢。

**Comment by 1a2s3d4f1** [comment]
更新optifine到OptiFine 1.14.4 HD U F4试试 ：https://optifine.net/downloads
测试OptiFine 1.14.4 HD U F4无法出现问题

**Comment by ruhuasiyu** [comment]
我确实看到很多人用光影玩的，按理说应该是可以的，可能是部分版本不行吧……
