### ISSUE TITLE
Bug 反馈

### ISSUE THREAD

**Issue by Haocen2004** [ruhuasiyu/CraftingPlusPlus#5]
1. 在1.13的测试版中村庄箱子里的居民之证的 NBT 标签不对 无法参与合成
2. 也是这个版本 合成画的 Function 未加入主时钟，合成必须手动执行 Function

建议：多增加点可以方便自定义的项目 
还有，我觉得图腾柱材质太难看了，能不能换成石砖啊qwq

**Comment by ruhuasiyu** [comment]
还没写完，有些namespace之类的还没修改好。然后，“多增加点可以方便自定义的项目”是何意？

**Comment by ruhuasiyu** [comment]
另外就是现在在技术性调整

**Comment by ruhuasiyu** [comment]
Fixed
