### ISSUE TITLE
Bug list (please report here)

### ISSUE THREAD

**Issue by ruhuasiyu** [ruhuasiyu/CraftingPlusPlus#8]
1. 手持机器背景板不会消失，但是并不能使用
结果：不再出现

2. 魔法作物会闪烁
结果：未能解决。

4. 魔法树苗有时候会变成普通树苗
结果：未能解决。

6. 发射器向方块发射附魔之瓶固定掉落7-11点经验值
结果：未能解决。

7. 玩家有经验的时候无法制作附魔之瓶
结果：未复现。

8. 多功能一体机偶尔失效且迅速消耗经验
结果：未复现。

**Comment by ch-yx** [comment]
请把roose0.json改成`{"ambientocclusion": false, "textures": {"fan": "craftingpp:tool/roost", "particle": "craftingpp:tool/roost"}, "display": {"head": {"rotation": [0, 0, 0], "translation": [0, -12, 0], "scale": [2.4, 2.4, 2.4]}}, "elements": [{"from": [8, 0, 0], "to": [24, 0.001, 16], "rotation": {"origin": [8, 0, 0], "axis": "z", "angle": 22.5, "rescale": false}, "shade": false, "faces": {"up": {"uv": [0, 0, 16, 16], "texture": "#fan", "rotation": 90}, "down": {"uv": [0, 16, 16, 0], "texture": "#fan", "rotation": 270}}}, {"from": [-8, 0, 0], "to": [8, 0.001, 16], "rotation": {"origin": [8, 0, 0], "axis": "z", "angle": -22.5, "rescale": false}, "shade": false, "faces": {"up": {"uv": [0, 0, 16, 16], "texture": "#fan", "rotation": 270}, "down": {"uv": [0, 16, 16, 0], "texture": "#fan", "rotation": 90}}}, {"from": [0, 0, 8], "to": [16, 0.001, 24], "rotation": {"origin": [0, 0, 8], "axis": "x", "angle": -22.5, "rescale": false}, "shade": false, "faces": {"up": {"uv": [16, 16, 0, 0], "texture": "#fan"}, "down": {"uv": [16, 0, 0, 16], "texture": "#fan"}}}, {"from": [0, 0, -8], "to": [16, 0.001, 8], "rotation": {"origin": [0, 0, 8], "axis": "x", "angle": 22.5, "rescale": false}, "shade": false, "faces": {"up": {"uv": [0, 0, 16, 16], "texture": "#fan"}, "down": {"uv": [0, 16, 16, 0], "texture": "#fan"}}}]}`

**Comment by ch-yx** [comment]
本来是打算干脆删掉背面的
但是看起来效果不太好
于是改了一点点

**Comment by ch-yx** [comment]
为啥c lo se了？
